<p style="text-align:center">
    <a href="https://skills.network/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkML0101ENSkillsNetwork20718538-2022-01-01">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="200" alt="Skills Network Logo"  />
    </a>
</p>

<h1 align="center"><font size="5">Final Project: Classification with Python</font></h1>


# About The Dataset


The original source of the data is Australian Government's Bureau of Meteorology and the latest data can be gathered from [http://www.bom.gov.au/climate/dwo/](http://www.bom.gov.au/climate/dwo/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkML0101ENSkillsNetwork20718538-2022-01-01).

The dataset to be used has extra columns like 'RainToday' and our target is 'RainTomorrow', which was gathered from the Rattle at [https://bitbucket.org/kayontoga/rattle/src/master/data/weatherAUS.RData](https://bitbucket.org/kayontoga/rattle/src/master/data/weatherAUS.RData?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkML0101ENSkillsNetwork20718538-2022-01-01)



This dataset contains observations of weather metrics for each day from 2008 to 2017. The **weatherAUS.csv** dataset includes the following fields:

| Field         | Description                                           | Unit            | Type   |
| ------------- | ----------------------------------------------------- | --------------- | ------ |
| Date          | Date of the Observation in YYYY-MM-DD                 | Date            | object |
| Location      | Location of the Observation                           | Location        | object |
| MinTemp       | Minimum temperature                                   | Celsius         | float  |
| MaxTemp       | Maximum temperature                                   | Celsius         | float  |
| Rainfall      | Amount of rainfall                                    | Millimeters     | float  |
| Evaporation   | Amount of evaporation                                 | Millimeters     | float  |
| Sunshine      | Amount of bright sunshine                             | hours           | float  |
| WindGustDir   | Direction of the strongest gust                       | Compass Points  | object |
| WindGustSpeed | Speed of the strongest gust                           | Kilometers/Hour | object |
| WindDir9am    | Wind direction averaged of 10 minutes prior to 9am    | Compass Points  | object |
| WindDir3pm    | Wind direction averaged of 10 minutes prior to 3pm    | Compass Points  | object |
| WindSpeed9am  | Wind speed averaged of 10 minutes prior to 9am        | Kilometers/Hour | float  |
| WindSpeed3pm  | Wind speed averaged of 10 minutes prior to 3pm        | Kilometers/Hour | float  |
| Humidity9am   | Humidity at 9am                                       | Percent         | float  |
| Humidity3pm   | Humidity at 3pm                                       | Percent         | float  |
| Pressure9am   | Atmospheric pressure reduced to mean sea level at 9am | Hectopascal     | float  |
| Pressure3pm   | Atmospheric pressure reduced to mean sea level at 3pm | Hectopascal     | float  |
| Cloud9am      | Fraction of the sky obscured by cloud at 9am          | Eights          | float  |
| Cloud3pm      | Fraction of the sky obscured by cloud at 3pm          | Eights          | float  |
| Temp9am       | Temperature at 9am                                    | Celsius         | float  |
| Temp3pm       | Temperature at 3pm                                    | Celsius         | float  |
| RainToday     | If there was rain today                               | Yes/No          | object |
| RISK_MM       | Amount of rain tomorrow                               | Millimeters     | float  |
| RainTomorrow  | If there is rain tomorrow                             | Yes/No          | float  |

Column definitions were gathered from [http://www.bom.gov.au/climate/dwo/IDCJDW0000.shtml](http://www.bom.gov.au/climate/dwo/IDCJDW0000.shtml?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkML0101ENSkillsNetwork20718538-2022-01-01)



## **Import the required libraries**


In [112]:
# All Libraries required for this lab are listed below. The libraries pre-installed on Skills Network Labs are commented.
# !mamba install -qy pandas==1.3.4 numpy==1.21.4 seaborn==0.9.0 matplotlib==3.5.0 scikit-learn==0.20.1
# Note: If your environment doesn't support "!mamba install", use "!pip install"

In [113]:
# Surpress warnings:
def warn(*args, **kwargs):
    pass
import warnings
warnings.warn = warn

In [114]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
from sklearn import preprocessing
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn import svm
from sklearn.metrics import jaccard_score
from sklearn.metrics import f1_score
from sklearn.metrics import log_loss
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, accuracy_score
import sklearn.metrics as metrics

### Importing the Dataset


In [115]:
df = pd.read_csv('https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-ML0101EN-SkillUp/labs/ML-FinalAssignment/Weather_Data.csv')

df.head()

Date  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine WindGustDir  \
0  2/1/2008     19.5     22.4      15.6          6.2       0.0           W   
1  2/2/2008     19.5     25.6       6.0          3.4       2.7           W   
2  2/3/2008     21.6     24.5       6.6          2.4       0.1           W   
3  2/4/2008     20.2     22.8      18.8          2.2       0.0           W   
4  2/5/2008     19.7     25.7      77.4          4.8       0.0           W   

   WindGustSpeed WindDir9am WindDir3pm  ...  Humidity9am  Humidity3pm  \
0             41          S        SSW  ...           92           84   
1             41          W          E  ...           83           73   
2             41        ESE        ESE  ...           88           86   
3             41        NNE          E  ...           83           90   
4             41        NNE          W  ...           88           74   

   Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RainToday  \
0       1017.6       1017.4         8         8     20.7     20.9        Yes   
1       1017.9       1016.4         7         7     22.4     24.8        Yes   
2       1016.7       1015.6         7         8     23.5     23.0        Yes   
3       1014.2       1011.8         8         8     21.4     20.9        Yes   
4       1008.3       1004.8         8         8     22.5     25.5        Yes   

   RainTomorrow  
0           Yes  
1           Yes  
2           Yes  
3           Yes  
4           Yes  

[5 rows x 22 columns]

### Data Preprocessing


#### Transforming Categorical Variables


First, we need to convert categorical variables to binary variables. We will use pandas `get_dummies()` method for this.


In [116]:
df_sydney_processed = pd.get_dummies(data=df, columns=['RainToday', 'WindGustDir', 'WindDir9am', 'WindDir3pm'])

Next, we replace the values of the 'RainTomorrow' column changing them from a categorical column to a binary column. We do not use the `get_dummies` method because we would end up with two columns for 'RainTomorrow' and we do not want, since 'RainTomorrow' is our target.


In [117]:
df_sydney_processed.replace(['No', 'Yes'], [0,1], inplace=True)

### Training Data and Test Data


Now, we set our 'features' or x values and our Y or target variable.


In [118]:
df_sydney_processed.drop('Date',axis=1,inplace=True)

In [119]:
df_sydney_processed = df_sydney_processed.astype(float)

In [120]:
features = df_sydney_processed.drop(columns='RainTomorrow', axis=1)
Y = df_sydney_processed['RainTomorrow']

### Linear Regression


####  Use the `train_test_split` function to split the `features` and `Y` dataframes with a `test_size` of `0.2` and the `random_state` set to `10`.


In [121]:
#Enter Your Code, Execute and take the Screenshot
#Normalizing the Data
from sklearn.preprocessing import StandardScaler
features=preprocessing.StandardScaler().fit(features).transform(features)
features[0:5]

array([[ 1.01512601, -0.13507807,  1.23613927,  0.37146005, -1.87896481,
        -0.04408087,  0.27304105,  0.09468284,  1.57493504,  1.80020165,
        -0.10463342,  0.19902353,  1.45711035,  1.58608764,  0.58822905,
        -0.1498131 , -1.6890139 ,  1.6890139 , -0.19683104, -0.26458131,
        -0.2114572 , -0.0962102 , -0.23341161, -0.21846239, -0.12709872,
        -0.14570551, -0.23341161, -0.14570551, -0.28075943, -0.22900939,
        -0.12459185,  1.13817336, -0.15731934, -0.20667842, -0.21224496,
        -0.15731934, -0.20667842, -0.1775832 , -0.1583367 , -0.16724183,
        -0.18031258, -0.16333775,  4.46855108, -0.1775832 , -0.19599158,
        -0.24484312, -0.1319786 , -0.79155161, -0.4172346 , -0.17481649,
        -0.48552917, -0.34946664, -0.33553693, -0.1319786 , -0.33327672,
        -0.13899878, -0.10841489, -0.13553087, -0.28454344, -0.26458131,
        -0.30236527,  4.5774469 , -0.11266543, -0.25587558, -0.24343717,
        -0.18742087],
       [ 1.01512601,  0.57871

In [122]:
x_train, x_test, y_train, y_test = train_test_split(features, Y, test_size=0.2, random_state=10)

#### Create and train a Linear Regression model called LinearReg using the training data (`x_train`, `y_train`).


In [123]:
LinearReg = LinearRegression()
LinearReg.fit(x_train, y_train)

LinearRegression()

#### Now use the `predict` method on the testing data (`x_test`) and save it to the array `predictions`.


In [124]:
#Enter Your Code, Execute and take the Screenshot

In [125]:
predictions = LinearReg.predict(x_test)
print(predictions [0:5])
y_test[0:5]

[0.13104462 0.26507782 0.9843161  0.28729462 0.1237204 ]


3066    0.0
2456    0.0
1629    1.0
838     1.0
2506    0.0
Name: RainTomorrow, dtype: float64

#### Using the `predictions` and the `y_test` dataframe calculate the value for each metric using the appropriate function.


In [126]:
LinearRegression_MAE = np.mean(np.abs(predictions-y_test))
LinearRegression_MSE = np.mean((predictions-y_test)**2)
LinearRegression_R2 = 1-(np.sum((y_test-predictions)**2)/np.sum((y_test-np.mean(y_test))**2))

#### Show the MAE, MSE, and R2 in a tabular format using data frame for the linear model.


In [127]:
Report = {'MAE': [LinearRegression_MAE], 'MSE': [LinearRegression_MSE], 'R2': [LinearRegression_R2]}
Report = pd.DataFrame(data=Report)
Report

MAE       MSE        R2
0  0.255701  0.115779  0.426841

### KNN


#### Create and train a KNN model called KNN using the training data (`x_train`, `y_train`) with the `n_neighbors` parameter set to `4`.


In [128]:
KNN = KNeighborsClassifier(n_neighbors = 4).fit(x_train,y_train)

#### Now use the `predict` method on the testing data (`x_test`) and save it to the array `predictions`.


In [129]:
predictions = KNN.predict(x_test)
print(predictions[0:5])
y_test[0:5]

[0. 1. 1. 1. 0.]


3066    0.0
2456    0.0
1629    1.0
838     1.0
2506    0.0
Name: RainTomorrow, dtype: float64

#### Using the `predictions` and the `y_test` dataframe calculate the value for each metric using the appropriate function.


In [130]:
KNN_Accuracy_Score = metrics.accuracy_score(y_test, predictions)
KNN_JaccardIndex = metrics.jaccard_score(y_test, predictions)
KNN_F1_Score = metrics.f1_score(y_test, predictions)

### Decision Tree


#### Create and train a Decision Tree model called Tree using the training data (`x_train`, `y_train`).


In [131]:
#Enter Your Code, Execute and take the Screenshot

In [132]:
Tree = DecisionTreeClassifier(criterion="entropy", max_depth = 4)
Tree.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=4)

#### Now use the `predict` method on the testing data (`x_test`) and save it to the array `predictions`.


In [133]:
predictions = Tree.predict(x_test)
print(predictions [0:5])
y_test[0:5]

[0. 0. 1. 0. 0.]


3066    0.0
2456    0.0
1629    1.0
838     1.0
2506    0.0
Name: RainTomorrow, dtype: float64

#### Using the `predictions` and the `y_test` dataframe calculate the value for each metric using the appropriate function.


In [134]:
Tree_Accuracy_Score = metrics.accuracy_score(y_test, predictions)
Tree_JaccardIndex = metrics.jaccard_score(y_test, predictions)
Tree_F1_Score = metrics.f1_score(y_test, predictions)

### Logistic Regression


#### Use the `train_test_split` function to split the `features` and `Y` dataframes with a `test_size` of `0.2` and the `random_state` set to `1`.


In [135]:
x_train, x_test, y_train, y_test = train_test_split(features,Y, test_size=0.2, random_state=1)

#### Create and train a LogisticRegression model called LR using the training data (`x_train`, `y_train`) with the `solver` parameter set to `liblinear`.


In [136]:
LR = LogisticRegression(C=0.01, solver='liblinear').fit(x_train,y_train)

#### Now, use the `predict` method on the testing data (`x_test`) and save it to the array `predictions`.


In [137]:
predictions = LR.predict(x_test)
predictions_prob = LR.predict_proba(x_test)
print(predictions [0:5])
y_test[0:5]

[0. 0. 0. 0. 0.]


255     0.0
1552    0.0
1353    0.0
1060    0.0
808     0.0
Name: RainTomorrow, dtype: float64

#### Using the `predictions` and the `y_test` dataframe calculate the value for each metric using the appropriate function.


In [138]:
LR_Accuracy_Score = metrics.accuracy_score(y_test,predictions)
LR_JaccardIndex = metrics.jaccard_score(y_test,predictions)
LR_F1_Score = metrics.f1_score(y_test,predictions)
LR_Log_Loss = metrics.log_loss(y_test,predictions_prob)

### SVM


#### Create and train a SVM model called SVM using the training data (`x_train`, `y_train`).


In [139]:
SVM = svm.SVC(kernel='rbf')
SVM.fit(x_train, y_train)

SVC()

#### Now use the `predict` method on the testing data (`x_test`) and save it to the array `predictions`.


In [140]:
predictions = SVM.predict(x_test)

#### Using the `predictions` and the `y_test` dataframe calculate the value for each metric using the appropriate function.


In [141]:
SVM_Accuracy_Score = metrics.accuracy_score(y_test, predictions)
SVM_JaccardIndex = metrics.jaccard_score(y_test, predictions)
SVM_F1_Score = metrics.f1_score(y_test, predictions)

### Report


#### Show the Accuracy,Jaccard Index,F1-Score and LogLoss in a tabular format using data frame for all of the above models.

\*LogLoss is only for Logistic Regression Model


In [142]:
Report={'Algorithm': ['KNN'], 'Accuracy': [KNN_Accuracy_Score], 'F1-score': [KNN_F1_Score], 'Jaccard': [KNN_JaccardIndex]}
Report1={'Algorithm': ['Decision Tree'], 'Accuracy': [Tree_Accuracy_Score], 'F1-score': [Tree_F1_Score], 'Jaccard': [Tree_JaccardIndex]}
Report2={'Algorithm': ['SVM'], 'Accuracy': [SVM_Accuracy_Score], 'F1-score': [SVM_F1_Score], 'Jaccard': [SVM_JaccardIndex]}
Report3={'Algorithm': ['LogisticRegression'], 'Accuracy': [LR_Accuracy_Score], 'F1-score': [LR_F1_Score], 'Jaccard': [LR_JaccardIndex], 'LogLoss': [LR_Log_Loss]}
dictlist = [dict() for x in range(4)]
dictlist[0] = Report
dictlist[1] = Report1
dictlist[2] = Report2
dictlist[3] = Report3
dictlist=pd.DataFrame(data=dictlist)
dictlist

Algorithm              Accuracy              F1-score  \
0                 [KNN]  [0.7603053435114504]  [0.3891050583657587]   
1       [Decision Tree]  [0.8183206106870229]  [0.6489675516224188]   
2                 [SVM]  [0.8290076335877863]  [0.6363636363636364]   
3  [LogisticRegression]  [0.8259541984732824]  [0.6686046511627907]   

                 Jaccard                LogLoss  
0  [0.24154589371980675]                    NaN  
1  [0.48034934497816595]                    NaN  
2   [0.4666666666666667]                    NaN  
3   [0.5021834061135371]  [0.38860313858091705]